FROM ruby:3.3.0-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev curl \
    libjemalloc2 libvips sqlite3 node-gyp pkg-config python-is-python3 \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Rails app lives in /rails
WORKDIR /rails

# Install JavaScript dependencies
ARG NODE_VERSION=21.7.3
ARG YARN_VERSION=1.22.22
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Install node modules
COPY package.json yarn.lock ./
RUN yarn install

# Add a script to be executed every time the container starts
COPY bin/docker-entrypoint-dev.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint-dev.sh
ENTRYPOINT ["/usr/bin/docker-entrypoint-dev.sh"]

# Configure the main process to run when running the image
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"] 