version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0 -p 3000 --ssl --ssl-key=config/ssl/localhost-key.pem --ssl-cert=config/ssl/localhost.pem
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"  # Alternative HTTPS port
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgres://postgres:password@db:5432/fleet_core_engine_development
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fleet_core_engine_development
    ports:
      - "5434:5432"

volumes:
  postgres_data:
  node_modules: 